# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Careful Examination
author: bwv549
email: faenrandir@gmail.com
reddit_username: bwv549
category-list: [Truth-Claims, Sociology and Psychology, Neo-Apologetics]
google_analytics: "UA-125187615-1"

description: >-
  Resources, research, and thoughts related to the truth-claims, teachings,
  and culture of The Church of Jesus Christ of Latter-day Saints (aka the Mormon Church).
baseurl: "/a_careful_examination" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  faenrandir

# instead of _site
destination: docs

header_pages:
  - about.md

# Build settings
markdown: kramdown
theme: minima

kramdown:
  # add anchor links with this
  # https://milanaryal.com.np/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/
  auto_ids: true

plugins:
  - jekyll-last-modified-at
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
